### ISSUE TITLE
Introduce Spark Connector

### ISSUE THREAD

**Issue by sam-h-bean** [weaviate/weaviate#2076]
It would be great to be able to ingest data into a Weaviate with a Spark DataFrameWriter. This would allow easier integration for those who are currently using Lakehouse architectures to pump data into a search backend. Similar functionality to the elasticsearch-spark connector.

**Comment by illagrenan** [comment]
I think this is a great idea. Ideally, there should be a single interface for connectors. The community could then write their own connectors. I'd love to tell Weaviate where the data are, and then Weaviate would take care of the import itself.

**Comment by samos123** [comment]
Sounds like highest priority would be to support writing to Weaviate from Spark but end goal would be to support both reading from Weaviate into Spark and writing into Weaviate. 

The [Neo4j Spark](https://github.com/neo4j-contrib/neo4j-spark-connector/tree/5.0), [Mongo Spark](https://github.com/mongodb/mongo-spark) and [ElasticSearch Spark](https://github.com/elastic/elasticsearch-hadoop/tree/main/spark/core/src/main/scala/org/elasticsearch/spark) connectors are good reference examples. Instead we would use the [Weaviate java client](https://github.com/semi-technologies/weaviate-java-client) to write to Weaviate. This guide has a good explanation of what's needed to [write a connector from scratch](https://levelup.gitconnected.com/easy-guide-to-create-a-write-data-source-in-apache-spark-3-f7d1e5a93bdb).

Open questions:
1. What language to use for the Weaviate connector? Scala or Java? 
2. What version of Spark should we target? 
3. Should the Spark connector create the Weaviate Schema automatically for you if it doesn't exist?
4. When to convert a spark string to Weaviate string and when to convert Spark string to Weaviate text?

Answering the questions myself but please chip in if you have an opinion on them:
1. My preference would be Scala since the Neo4j  and ES example uses Scala and seems to implement options in a similiar way like we would need them.
2. Only 3.0 and above because there were API changes
3. I think that would be the best UX, but maybe 1st version this won't be there?
4. Only relevant when we do automatic schema creation. I don't think there is a straight forward answer for this and we might need this to be configurable with a good default. We could have this is an option and you would have to set this option before writing. The default could be treat all strings as text?

**Comment by bobvanluijt** [comment]
For those interested in this, we are starting the endeavor up. In case you're interested in helping, please reach out to me on our [Weaviate Slack channel](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw). Thanks

**Comment by sam-h-bean** [comment]
Would we want the ability to extract the vectors from weaviate as well? I can imagine a use case where the vectorization is delegated to the database but we would like to extract the vectors to a data lake such that re-ingestion would not require doing vectorization again. You could just read the embeddings from the parquet files and supply them on the ingest.

**Comment by bobvanluijt** [comment]
That makes sense.

Two things to note.

1. We are working on a [scroll API](https://github.com/semi-technologies/weaviate/issues/2302). You might want to use this in this feature.
2. We are packaging [this](https://gist.github.com/bobvanluijt/39b9e9874227d03747e777317b203bc4) up in Parquet files as well before we release it to the world. Maybe nice to test this out when the connector is done.

**Comment by dirkkul** [comment]
closing as this is released
