### ISSUE TITLE
feat(proposal, docs): nearVector search to accept `vectorWeights` to filter based on prioritised vector properties

### ISSUE THREAD

**Issue by faivalete** [weaviate/weaviate#2388]
vectorWeights https://github.com/semi-technologies/weaviate/issues/1645 seems to be a property used in the past. 
As vector query engine is amazing how weaviate performs. 

When using weaviate with self-generated vectors would be very useful to return results based on more than 3 params.
https://weaviate.io/developers/weaviate/current/graphql-references/vector-search-parameters.html

vectorWeights could provide some kind of weight where: you need to query against a property of the vector to be more weighted than others.

Is there a way to achieve this with the current vector search API?

**Comment by etiennedi** [comment]
Do I understand it correctly that you would like to influence the distance calculation for a given vector? E.g. if someone uses `dot product` and has a 3-dimensional vector, instead of the dot product using all 3 dimensions with equal weight, there should be a specific option to give more weight a dimension.

If so this would have to happen at index time already because the vector index is built up based on vector proximity which in turn makes use of the distance calculation. So if this is indeed what you mean, this could not be changed at query time.

**Comment by faivalete** [comment]
was the issue addressed? 
* Which could be some alternative solutions?

have:

```javascript
const  vectorSchemaOne = [0, 0.5]; // prop[0] means the probability of being a pet of type 'cat', prop[1] means the probability of being a pet eating 'meat'
const  vectorSchemaTwo = [1, null]; // I want only probable cats, don't want to know what they eat. 

 return client.graphql
              .get()
              .withClassName("commonSchema")
              .withFields("a b c _additional {certainty}")
              .withNearVector({ vector: vectorSchemaTwo , certainty: 0.1 })
              .do()
              .then((nearest) => {

```
