### ISSUE TITLE
[bug] Operator "Equal" returns elements containing

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#2580]
HI,

As shown below, a query with an "Equal" operator returns elements only containing the value.

![image](https://user-images.githubusercontent.com/1785759/215513025-7e4c5860-d22e-4e4d-8be0-5b9cfbc19d9e.png)

**Comment by trengrj** [comment]
Hi @eostis , this is due to the default `tokenization` being set as `word` on the string type. Fix would be to change `tokenization` to `field` in the schema.

<img width="882" alt="Screen Shot 2023-02-09 at 5 13 51 pm" src="https://user-images.githubusercontent.com/2173919/217743202-ad1550c5-63f0-41bc-9562-c7d8a3d57553.png">

**Comment by eostis** [comment]
Thanks @trengrj.Makes sense.

Link to the documentation: https://weaviate.io/developers/weaviate/configuration/schema-configuration#property-tokenization
