### ISSUE TITLE
Support workload identity for `backup-gcs` module (GCS backups)

### ISSUE THREAD

**Issue by iamcaleberic** [weaviate/weaviate#2619]
Currently the backup-gcs module only supports JSON keys, it does not support workload identity.

> Workload Identity allows a Kubernetes service account in your GKE cluster to act as an IAM service account. Pods that use the configured Kubernetes service account automatically authenticate as the IAM service account when accessing Google Cloud APIs. Using Workload Identity allows you to assign distinct, fine-grained identities and authorization for each application in your cluster.

https://github.com/weaviate/weaviate/blob/fcc1f8470bfbe5f71a6efb45075a3e06f66f5f40/modules/backup-gcs/client.go#L37

it should be possible to use workload identity for GCS backups instead of relying on passing JSON keys. Many large enterprise have an org policy that prevents them from downloading JSON keys for service accounts.

https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity

**Comment by etiennedi** [comment]
Wondering if this is a bug or a missing feature. Would this line discover workload identity credentials: https://github.com/weaviate/weaviate/blob/fcc1f8470bfbe5f71a6efb45075a3e06f66f5f40/modules/backup-gcs/client.go#L41

But we don't let it because we only ever get there if the env var is set? Or would we have to do something specifically to support it?

cc @parkerduckworth

**Comment by iamcaleberic** [comment]
I would say its more an update, to allow use of workload Identity, all that needs to be removed is the json application credentials check because the Google api checks for application default credentials in order defined here

https://cloud.google.com/docs/authentication/application-default-credentials#search_order

The current check for the json key interrupts that.
