### ISSUE TITLE
Summarization (SUM) module -> Killed

### ISSUE THREAD

**Issue by mloenow** [weaviate/weaviate#2622]
I'm trying to get the Summarization (SUM) module to run using the exact configuration specified at https://weaviate.io/developers/weaviate/modules/reader-generator-modules/sum-transformers#how-to-enable-module-configuration, but it keeps getting killed.

My machine is Apple Silicon, so I've tried to disable CUDA via environment variable, which has worked fine for other modules. Besides the image specified in the documentation, I've also tried the more platform specific semitechnologies/sum-transformers:facebook-bart-large-cnn-onnx-arm64-1.2.0 image.

What can I do to debug the issue? I tried setting various environment variables for logging level (e.g. `LOG_LEVEL='debug'`), and also overwriting the start command to include the --log_level flag, but nothing has worked.

The only output I get is:

```
2023-02-13 15:48:05 The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]5 
2023-02-13 15:48:06 INFO:     Started server process [7]
2023-02-13 15:48:06 INFO:     Waiting for application startup.
2023-02-13 15:48:06 INFO:     Running on CPU
2023-02-13 15:48:06 INFO:     Running using ONNX runtime
2023-02-13 15:48:05 Moving 0 files to the new cache system
2023-02-13 15:48:09 Killed
```

**Comment by etiennedi** [comment]
Hi @mloenow,

thanks for your interest and welcome to our community. Let me see if we can get this running:

I'm going to make a few assumptions, if they're incorrect, please let me know:

* You're running with Docker
* You have the "Docker for Mac" toolchain installed which has CPU and memory limits set by default
* The reason for the kill is an OOM-kill because the summarizer container wants to use more memory than Docker allows.

To debug this, you can run `docker stats` which the container is running/starting, you should see the memory for the summarizer container go up until it eventually gets killed. Once killed you can also check the exit status (and I think there is even an explicit OOMKilled field) using `docker inspect <containerId>`.

If this all turns out correct, you can adjust the memory limit for the Docker VM in the Docker for Mac GUI. For example, this is what it would currently look like for me: 
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/8974479/218957725-f5b1861b-54f4-4705-ae4f-61eefd145992.png">

Hope this helps.

PS: Have you already discovered our [Slack channel](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw)? There we have lots of active Weaviate users ready to help each other debug issues like this. Often this is much faster than getting an answer on a GH issue, as it's mainly Weaviate team members who go through the issues. (You were a bit lucky that I was looking for another issue and came across yours by accident).

**Comment by mloenow** [comment]
Hi Etienne,

Thanks for getting back to me!

It was indeed an OOM-kill as confirmed by the `docker inspect` command (`[{ ... "State": { ... "OOMKilled": true ... } } ...]`). Bumping up the memory limit fixed this problem. Did not think the issue could be outside of the application context 🤦‍♂️

Will get on your Slack later today - thanks!

P.S. May I direct you attention to https://github.com/weaviate/weaviate/issues/2335#issuecomment-1428712010 (re: handling large number of tokens).
