### ISSUE TITLE
Allow class deletion when store is read only

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#2778]
If Weaviate goes read only due to disk or memory pressure it should still allow for class deletion. Currently the following happens:

```
UnexpectedStatusCodeException: Delete class from schema! Unexpected status code: 400, with response body:
 {'error': [{'message': "delete idx for class 'Bp4sfpwpu6_kb': drop index bp4sfpwpu6_kb: delete shard
 bp4sfpwpu6_kb_a081Hc7O9RH4: store is read-only"}]}.
```

**Comment by etiennedi** [comment]
Good point. It makes sense that object deletes are prevented because they would (at least initially) lead to an increase in resources. But a class delete will certainly reduce both memory and disk usage.

I _assume_ this is currently because it probably tries to flush everything before deleting (as delete is implemented similar to a shutdown). If the class is deleted anyway, it doesn't matter if something can't be flushed. So we could construct this in a way that (some) errors during class shutdown are ignored and the class can get deleted - even when it's read-only.
