### ISSUE TITLE
[BUG] invalid pagination params: query maximum results exceeded?

### ISSUE THREAD

**Issue by scruel** [weaviate/weaviate#2929]
I stored `102980` objects in the database, when I set offset to `10000` with limit set to `1`, it gives me the following error:
```
{'data': {'Get': {'Document': None}}, 'errors': [{'locations': [{'column': 6, 'line': 1}], 'message': 'explorer: list class: search: invalid pagination params: query maximum results exceeded', 'path': ['Get', 'Document']}]}
```
![image](https://user-images.githubusercontent.com/16933298/233572391-594010cb-ec41-4f70-b754-3111e640f07d.png)

Why this happened, also how can I set the page size rather than limit?

**Comment by trengrj** [comment]
You can increase the `QUERY_MAXIMUM_RESULTS` environment variable to increase this limit.

Additionally on a recent version of Weaviate you can now use the cursor api https://weaviate.io/developers/weaviate/api/graphql/filters#cursor-with-after to page through all results.

**Comment by scruel** [comment]
> You can increase the `QUERY_MAXIMUM_RESULTS` environment variable to increase this limit.

Can you check the issue content? I only query for one result with limit equal to 1...

**Comment by byronvoorbach** [comment]
Hi @scruel 👋

The reason you’re getting this error is outlined[here](https://weaviate.io/developers/weaviate/api/graphql/filters#performance-and-resource-considerations--limitations) 

Effectively when searching for search results with offset 10,000 and a limit of 1, Weaviate will have to internally retrieve 10001 search results and discard results 0-10,000 before serving them to the user. We have a soft limit on 10k results, which is why you are getting the error. My colleague @trengrj  mentioned how to increase this value.

I hope this clears things up!

**Comment by yihui504** [comment]
Thanks for pointing me to #2929. I've reviewed it carefully, and I believe this is a **different issue** with a different focus:

**#2929** (closed, 2023): Reports that `offset=10000 + limit=1` on the **GraphQL Get endpoint** triggers "query maximum results exceeded". The user was confused about why a valid-looking pagination request was rejected. The issue was closed with the explanation that `QUERY_MAXIMUM_RESULTS` is a soft limit.

**This issue**: Reports that `limit=10001` on the **REST list endpoint** (`GET /v1/objects`) returns **HTTP 500** instead of a proper **4xx validation error**. The core bug is not that the limit is enforced (that's expected behavior per #2929), but that the **HTTP status code is wrong**:

- Current: `500 Internal Server Error` — implies an unexpected server crash
- Expected: `400 Bad Request` or `422 Unprocessable Entity` — a predictable input validation failure

The error message itself is informative and correctly identifies the problem (referencing `QUERY_MAXIMUM_RESULTS` by name). The issue is purely the HTTP status code: 500 is semantically wrong for an input validation error, causes monitoring noise (false-positive 500 alerts), and is inconsistent with the same endpoint's behavior for other invalid inputs (e.g., `limit=not_a_number` correctly returns 422).

This is a **status code correctness issue**, not a "why is my query rejected" question.
