### ISSUE TITLE
Cannot change limit on aggregate query

### ISSUE THREAD

**Issue by david-waterworth** [weaviate/weaviate#3074]
I know that Get queries have a limit of 10_000 rows but I'm running into an issue where I'm only getting 100 rows back from an Aggregate query that should return ~4000. Unlike Get I don't see any option to increase this - it seems to be using the same default as Get but I don't see any way of increasing it (there's no `with_limit`).

**Comment by dandv** [comment]
You can use the GraphQL API to set the `limit` for an `Aggregate` query. If you try the query below on WCS, you'll see results beyond the default `100` limit:


```graphql
{
  Aggregate {
    JeopardyQuestion(
      groupBy: "answer"
      limit: 200
    ) {
      groupedBy {
        value
      }
      meta {
        count
      }
    }
  }
}
```

I'm going to close this issue since it's more of a support question, but if you need more help, please [start a discussion on the forum](https://forum.weaviate.io/c/support/6). I've also filed a feature request for the Python client to support `with_limit` on `.aggregate` for feature parity with GraphQL.
