### ISSUE TITLE
Hybrid search offset + limit is returning duplicate results consistently onto the next offset (page)

### ISSUE THREAD

**Issue by junbetterway** [weaviate/weaviate#3205]
We have encountered a weird behavior in our search engine using Hybrid search. First, we have upgraded our Weaviate core version to **1.19.9** (issue is also observed in **1.19.8**) in order to have the fix for this issue: https://github.com/weaviate/weaviate/issues/3076

Indeed after the fix for https://github.com/weaviate/weaviate/issues/3076 - I am not seeing anymore my first page results duplicated on succeeding pages. Meaning if my limit is 25 results per page, before the fix, I cannot get the 26th result onwards as page 2, 3, 4 and so on always show my page 1 results (top 25 always). Please see reported issue for more details.

However, now I am seeing another issue which I was not able to notice during my initial testing of the fix where there were some 2 or 3 results that are duplicated onto the next page thus, I thought it maybe a problem on my codebase. However, I go ahead and ran some CURL/GraphQL commands to our Weaviate schema and these are the results:

For the first page, `limit=5 & offset=0`

![image](https://github.com/weaviate/weaviate/assets/50645323/80f4c298-de4a-4999-a9c2-5d3b2d0e4562)

Please take note of the above two highlighted profiles: **"Tduiadtada Wsjjsyuncj"** and **"Andrew Go"**

For the second page, `limit=5 & offset=5`

![image](https://github.com/weaviate/weaviate/assets/50645323/e7b1e93f-bfdb-42ac-bd15-87f8a7d479e4)

As you can see, the above two profiles are duplicated from page 1 to page 2 (this is consistent and not sporadic) which got me thinking it might be possible that I have a duplicated record on the Weaviate database however, if you will check they both have the same vector UUID which should be unique. Though, for posterity - I did a query and it only returns one record for each so no duplicate records in my DB. Please see below query for **"Andrew Go"** 

<img width="515" alt="image" src="https://github.com/weaviate/weaviate/assets/50645323/5b5e878c-2d9b-4c84-90fb-601a2d75ed97">

Is there something missing on how I run my hybrid search using offset + limit? Or is this a bug continuation for hybrid search using offset?

**Comment by donomii** [comment]
Hi, thanks for your bug report.  I'm currently looking into this, but I am having trouble reproducing the issue.  Is it possible for me to download your data set so I can get exactly the same results as you?  Is the data set public?

**Comment by donomii** [comment]
Also, does this happen for every query, or only some queries?

**Comment by junbetterway** [comment]
Thanks for looking in to this @donomii :)

Every query but the trick to replicate is the offsetting part, when I am using 10 results per page - I am not seeing the issue but when I lowered it down to 5 results per page that's where I was able to reproduce it at least on my local. In our production though, it is set to 10 results per page so not sure 🤷‍♂️ 

Sure, I can you my schema and I can export my local data it should be same with what I reported which are my own imaginary profiles. I am still noob with Weaviate specially the management side, so can you guide me how I can export my dataset from my docker setup?

PS: Can you drop me email where I can send the files just too not expose it from here, our schema the very least? Thank you

**Comment by donomii** [comment]
It's probably better if you don't send us private data, I'll continue to work on our test data sets.

Thank you for your additional comment about 5 and 10 results per page, I think this is the important clue.  Hybrid search scores can change depending on the limit + offset, because hybrid ranking combines the scores from different searches.  When the limit is low (e.g. 5), some documents are excluded from the scoring.  When the limit is increased, the documents appear in multiple results(sparse and dense searches), so their ranking can change.

Could you do your test again?  Use offset=0, and set the limit=5 and limit=10.

If using a higher limit resolves the problem, then we recommend keeping the higher limit and discarding the extra results that you don't need.

**Comment by donomii** [comment]
It's caused by the hybrid algorithm.  I'll give a very quick example, for library books.  It's not a serious example, but it should show the problem

We're going to set alpha to 0.51, and search our imaginary library for books about "cats".  Weaviate does two searches, one keyword, one vector, and gets some results:

Limit = 1

keyword search
--------
"Pictures of cats" by A. Smith

vector search
-------
"How to keep pets" by B. Jones

alpha is set to 0.51, so the book on pets wins

Hybrid Result, limit=1
-------
"How to keep pets" by B. Jones


We're pretending that the vector search decided that the book "How to keep pets" was the best result for a query about cats.



Now we set the limit = 2

keyword search
--------
"Pictures of cats" by A. Smith
"All about cats" by C. Alan

vector search
-------
"How to keep pets" by B.Jones
"Pictures of cats" by A. Smith

Hybrid Results, limit = 2
-------
"Pictures of cats" by A. Smith
"How to keep pets" by B.Jones


The number one result of hybrid changed!  The first time, both books were equal, but we had a bias to vector search (0.51), so "How to keep pets" wins

But with limit = 2, "Pictures of cats" appears twice, so its score is now the highest.





We are currently planning to set the limit to 100 internally, so this doesn't happen anymore

**Comment by junbetterway** [comment]
Thanks for that explanation @donomii - just to ensure, I got it right with `alpha=0.51` then it favors vector search in your example.

**Keyword search:**
"Pictures of cats" by A. Smith
"All about cats" by C. Alan

**Vector search:**
"How to keep pets" by B.Jones
"Pictures of cats" by A. Smith

From what you've explained, it only points out that `"Pictures of cats" by A. Smith` won because it appear twice thus, it will have a higher score so the result will be:

**Hybrid Results, limit = 2:** (assuming this is offset=0 so this is page 1)
"Pictures of cats" by A. Smith       <-- this won since it appears twice
"How to keep pets" by B.Jones

however, it lacks continuation onto the next page behavior which is limit = 2 and offset = 2 (page 2) now how would this `"Pictures of cats" by A. Smith` still be part of the next results (**e.g.,** page 2, 3 or whichever page it will appear) if we already have the scores at hand during the query? Or maybe, I still lack understanding about this algorithm, so apologies.

In any case, do we mean the that this is inherent to hybrid search and the only way to avoid it, is to increase the results per page (or limit)? Setting it to **100** means I need to change the default `QUERY_DEFAULTS_LIMIT` which is set to **25** right?

Lastly, do you think it will be helpful if I can provide you my local dataset and schema? Or no point of doing it since you mentioned above that this is an inherent problem with hybrid algorithm? Thank you.
