### ISSUE TITLE
Replication consistency issue in Docker Multi node setup

### ISSUE THREAD

**Issue by ashokrajab** [weaviate/weaviate#3267]
## Overview
1. The attribute isConsistent seems to be unreliable.
2. `repair-on-read` doesn't seem to work as expected.

The script to reproduce the issue can be found [here](https://github.com/weaviate/weaviate/files/12068630/file_for_weaviate_issue_reproduce.zip).

## Issue
I'm trying to test replication in Docker multi node setup. So I have started 3 containers and performed the following actions:

1. With all the container running, I imported the data with consistency_level=weaviate.data.replication.ConsistencyLevel.QUORUM. Then I queried every docker container.
for the query:
client.query.get(class_name="Books", properties=["title"]) \
    .with_consistency_level(weaviate.data.replication.ConsistencyLevel.QUORUM) \
    .with_additional(["isConsistent"]) \
    .with_limit(3).do()
output:
{'data': {'Get': {'Books': [{'_additional': {'isConsistent': True},
     'title': 'Harry Potter and the Half-Blood Prince (Harry Potter#6)'},
    {'_additional': {'isConsistent': True},
     'title': 'Harry Potter Boxed Set  Books 1-5 (Harry Potter#1-5)'},
    {'_additional': {'isConsistent': True},
     'title': 'Molly Hatchet - 5 of the Best'}]}}}

But,
for the query:
client.query.get(class_name="Books", properties=["title"]) \
    .with_consistency_level(weaviate.data.replication.ConsistencyLevel.QUORUM) \
    .with_additional(["isConsistent"]) \
    .with_near_vector({"vector": query_book_vector}) \
    .with_limit(3).do()
output:
{'data': {'Get': {'Books': [{'_additional': {'isConsistent': False},
     'title': 'Harry Potter and the Half-Blood Prince (Harry Potter#6)'},
    {'_additional': {'isConsistent': False},
     'title': 'Unauthorized Harry Potter Book Seven News: "Half-Blood Prince" Analysis and Speculation'},
    {'_additional': {'isConsistent': False},
     'title': 'Harry Potter Collection (Harry Potter#1-6)'}]}}}

the isConsistent is False in the later case. **Expectation** is isConsistent to be True in the later case as well.

2. Lets consider container#1 is manually stopped while some new data is being imported into container#2 and container#3. After the import, container#1 is re-started.
note: All create object and get object query is done with consistency_level = QUORUM.

Now if you query to get some object from the new data with client pointing to container#1:
for query having with_where() - the response is empty.
for query having with_near_text() - the response is wrong. (My assumption: search is only carried out on data that is present in container#1 and **not** broadcasted to other two nodes and checked for results that is agreed by the QUORUM.) 
Expectation is to get the new data since the data is present in container#2 and#3, and the consistency in the get query is QUORUM. So it shouldn't matter that the concerned data is not present in container#1. I also **expected** the `repair-on-read` to kick in at this point to resolve the inconsistency in container#1. But that did not happen.

Now if you query to get some object from the new data with client pointing to container#2:
for query having with_where() - the response will contain the expected object.
for query having with_near_text() - the response will contain the expected object.

after the query with with_where, the concerned object is synced to container#1. But only the properties(ie., "title") are synced, the vector is empty for the object.
it is to be noted that the concerned object did not sync after the query having with_near_text(). So does this mean`repair-on-read` does not get triggered for vector search query?? 

performing the same query again with client pointing to container#1:
for query having with_where() - the response will contain the expected object. (here having .with_additional(["vector"]) you can see that its empty.)
for query having with_near_text() - the response is be wrong. (My assumption: This is because the vector for the concerned object is empty)

**Comment by ashokrajab** [comment]
I did extensive testing. And I can now confirm that:

The `repair-on-read` gets triggered only when you perform a query with `with_where()`. It does not get triggered when querying with `with_near_vector()`.

During the execution of `repair-on-read`, it updates all the attributes from the latest version of the object to the out-dated version of the object. While doing so, it sets the `vector` attribute as empty. As a result of this queries with `with_near_vector()` returns incorrect result.

**Comment by redouan-rhazouani** [comment]
Hi Ashok,

Thank you for raising this important ticket and for sharing your test results. We have identified two issues that I would like to address:

**Querying with `with_near_vector`:**
We acknowledge your observation regarding this type of request triggering a vector search. While vector search searches for objects, it does not ensure the consistency of the results. We have fixed this issue, and the fix will be included in the upcoming patch. @parkerduckworth 

**Querying with GraphQL and read repair limitations**:

When querying with GraphQL, there are three parts involved. 

1. The node performs the search.
2. It checks the consistency of the search results. 
3. It repairs any inconsistencies when possible.

In your case, Node-1 performed the search locally since the shards are local to that node. However, as all objects were imported while Node-1 was down, the search result set is empty from the node's perspective, leading to the first limitation you encountered.

In a real cluster, the node serving the client request can change for each request. So, use cases like yours are less common and not permanent. There is a good chance that the node handling subsequent requests will have the desired result.

There are two possible ways to trigger read repair. The first way is to query the node that has the data, such as Node-2. However, this is not guaranteed to be successful if Node-1 is not part of the quorum. While you would obtain consistent data according to the quorum, the data won't be repaired on Node-1.

The second way is to query the data from the node that has the data, such as Node-2, and specify the ALL consistency level. This ensures that you get consistent data and triggers repair across the entire cluster. After that, you can simply query the data from Node-1.

We understand that this may not be ideal for all scenarios. However, once we implement async repair, the nodes will be able to identify which nodes are missing updates and bring the cluster back in sync. This would make the remaining scenarios work out of the box without relying solely on read repair. Async repair is still on our roadmap for future enhancements.

It is worth mentioning that if you were using `client.data_object.get_id(),` the behavior would be as expected since it checks consistency on all nodes in the quorum, regardless of which node serves the request first.

I hope this explanation makes sense to you. If you have any further questions, please let me know.

**Comment by ashokrajab** [comment]
Hi Redouan,

Thank you for acknowledging and promptly working on a bugfix for `isConsistent` value in `with_near_vector()` query.

<hr>

Related to `repair-on-read` I need further clarification.

> In your case, Node-1 performed the search locally since the shards are local to that node. However, as all objects were imported while Node-1 was down, the search result set is empty from the node's perspective

Depicting a representation 3 node cluster with replication=3 and shardDesiredCount=3.

<table>
<tr>
<th> Node-1 </th>
<th> Node-2 </th>
<th> Node-3 </th>
</tr>
<tr>
<td> shard1 </td>
<td> shard2 </td>
<td> shard3 </td>
</tr>
<tr>
<td> shard2 </td>
<td> shard3 </td>
<td> shard1 </td>
</tr>
<tr>
<td> shard3 </td>
<td> shard1 </td>
<td> shard2 </td>
</tr>
</table>

Its clear that any given node will have all the shards to execute a query all by itself. So I agree with your response stating that "Node-1 performed the search locally since the shards are local to that node". But this should be the case only when the query is executed with `.with_consistency_level(weaviate.data.replication.ConsistencyLevel.ONE)`. 
If the consistency level is set as QUORUM or ALL, the query should have been broadcasted to all other nodes and the results should have been consolidated based on the result that is agreed by majority of the nodes.

So expectation is that node-1 should return the correct result despite not having update-to-date data when queried with QUORUM or ALL (also trigger `repair-on-read`).
Please correct me know if my expectation is not valid.

<hr>

> The second way is to query the data from the node that has the data, such as Node-2, and specify the ALL consistency level. This ensures that you get consistent data and triggers repair across the entire cluster. After that, you can simply query the data from Node-1.

Yes, I did try this, and yes it did trigger the `repair-on-read`. But the problem is: the repair is NOT done completely. The missing data object is created in node-1 with just properties(in our example its 'title'). The `vector` attribute is missing in the data object created in node-1.
I have reproduced this issue towards the end of the notebook that I have shared above. There you can see that after the `repair-on-read` completes, if you query node-1 with `.with_where()` to retrieve the newly created data object, you will get the same. But, if you query with `.with_near()` you will NOT get the newly created data object.
To simply put it, `repair-on-read` does account of updating the vector associated with the object being repaired (by virtue of this HNSW index is also not updated). So`.with_near()` query will return incorrect result after `repair-on-read`.

Hope this clarifies that the`eventually consistent` claim is not materialised. 

<hr>

If you need any further clarification, I would be happy to assist you with that. 

Looking forward to hearing from you.

Thanks,
Ashok.

**Comment by redouan-rhazouani** [comment]
Hi @ashokrajab

> Yes, I did try this, and yes it did trigger the repair-on-read. But the problem is: the repair is NOT done completely. The missing data object is created in node-1 with just properties(in our example its 'title'). The vector attribute is missing in the data object created in node-1.

Thanks for pointing that out! We've fixed the issue with vectors not being updated during read repair, and it'll be included in the upcoming patches. Your feedback is much appreciated!

**Comment by redouan-rhazouani** [comment]
Hi @ashokrajab

> So expectation is that node-1 should return the correct result despite not having update-to-date data when queried with QUORUM or ALL (also trigger repair-on-read).
> Please correct me if my expectation is not valid.

I understand your perspective, and I fully agree that the correct outcome should be consistent regardless of which node serves the query. It's worth mentioning that this is exactly the behavior when you try to retrieve a single object using `client.data_object_get_by_id`.

However, when querying using GQL, it's essential to note that under certain circumstances, this consistency may not be guaranteed, especially when querying from a node that has the shard locally but doesn't have the latest data.

To provide further context on how the search currently works:

1. The node performs a local search for data.
2. It checks the consistency of the search results.
3. The system attempts to repair any inconsistencies when possible.

The limitation arises because the node serving the request queries its local shards first and only looks to other nodes if a shard is not local to that specific node. The current trade-off is due to a couple of reasons: search is not a deterministic operation, and querying all the replicas at the same time is not efficient. In a real cluster, the node serving the client request can change for each query, leading to variations in results. While this issue might affect specific use cases, it is not a permanent concern, as subsequent requests may yield the desired outcome.

Once we implement async repairs, the system will be better equipped to maintain consistency across the cluster. This means that in your case, node-1 will fetch the latest update once it gets back online.

Thank you for bringing up this concern, and rest assured, we are committed to improving the system's performance and reliability. If you have any further questions or feedback, please don't hesitate to share them. Your input is invaluable in making our system even better.

**Comment by ashokrajab** [comment]
Thank you for the detailed response @redouan-rhazouani. 

I understand the limitation, but I have one concern with this. GQL not guaranteeing consistency also means that it does not trigger `repair-on-read`. So if we use Weaviate for purely vector search then inconsistency will never be resolved. 

This is a problem because, Weaviate is a vector search first db, so we cannot rely on `.with_where()` or `client. data_object_get_by_id()` queries to identify and resolve inconsistency.

Because of this we cannot be 100% certain that Weaviate will be **_eventually consistent_**.

**Comment by redouan-rhazouani** [comment]
Thank you for your valuable feedback @ashokrajab 

Regarding the specific test scenario with docker compose, it's indeed possible to encounter this limitation. However, it's essential to keep in mind that in a real cluster environment, the serving node selection is dynamic, which naturally triggers read-repair over time. As a result, this limitation is not commonly observed in real-world use cases.

Furthermore, I want to reiterate that we are actively working on implementing additional mechanisms beyond read repair to overcome this limitation entirely. By doing so, we aim to ensure a more robust and reliable experience for all use cases, including test scenarios

**Comment by ashokrajab** [comment]
@redouan-rhazouani,

I apologise if my response sounds repetitive. But I have to say that do not agree with these statements:

> which naturally triggers read-repair over time

Weavaite in its current form, triggers `repair-on-read` only for **non-vector search** queries. So when Weaviate is used for performing **only vector** search queries (`.near_vector()`) then `repair-on-read` will **never** be triggered. 
<br>
> As a result, this limitation is not commonly observed in real-world use cases.

I think you are basing this statement with the conception that Weaviate handles variety of queries. So at some point in time, the node with consistent data will process a non-vector search query, like `.with_where()` or `.data_object_get_by_id()` or `.with_after()` that will retrieve an object that is identified to be inconsistent with other replicas and there-by `repair-on-read` will be triggered.

But use case where Weaviate is used as a pure vector store db is highly likely. In such a use case Weaviate will be hit with only `.near_vector()` queries. In this case, if any inconsistency exist they will be never be resolved. Even if the _serving node selection is dynamic_, only when request lands on a node with consistent data, correct result will be returned. But every time when the request lands on the node with inconsistent data, it will continue to return incorrect result every time. 

I hope this clarifies. Please feel free to write back if anything is still not clear.

**Comment by redouan-rhazouani** [comment]
@ashokrajab 
My apologies for not being clear about what version of Weaviate I meant. I meant Weaviate with both bugs mentioned previously being fixed.

1. The first part of the fix you mentioned, which enables checking consistency including read repair on vector search, is already included in [Weaviate 1.20.2](https://github.com/weaviate/weaviate/releases/tag/v1.20.2).
2. As for the second issue where vectors were not being synced to the target node, [it will be resolved](https://github.com/weaviate/weaviate/pull/3280) in the upcoming patch release.

I hope that my previous answer is now clear and understandable.

**Comment by ashokrajab** [comment]
@redouan-rhazouani,

> As for the second issue where vectors were not being synced to the target node, https://github.com/weaviate/weaviate/pull/3280 in the upcoming patch release.

If I'm not wrong this fixes the issue where all the object properties are synced but the vector is not synced in the target node when `repair-on-read` is triggered as a result of non-vector search query (`.with_where()`).

But,

My concern that I have mentioned in the above [comment](https://github.com/weaviate/weaviate/issues/3267#issuecomment-1645300339) is related to `repair-on-read` NOT being triggered at all for `.near_vector()`. I believe the [bugfix](https://github.com/weaviate/weaviate/pull/3280) does not address this issue.

I hope this clarifies.

**Comment by redouan-rhazouani** [comment]
@ashokrajab 
> If I'm not wrong this fixes the issue where all the object properties are synced but the vector is not synced in the target node when repair-on-read is triggered as a result of non-vector search query (.with_where()).

That's partially correct since read repair works for both vector and non-vector searches. In this regard, they don't differ because it's the same process.

> My concern that I have mentioned in the above https://github.com/weaviate/weaviate/issues/3267#issuecomment-1645300339 is related to repair-on-read NOT being triggered at all for .near_vector(). I believe the https://github.com/weaviate/weaviate/pull/3280 does not address this issue.

This [fix](https://github.com/weaviate/weaviate/pull/3271) enables checking consistency including read repair on vector search (`.with_near_vector()`), is already included in [Weaviate 1.20.2](https://github.com/weaviate/weaviate/releases/tag/v1.20.2).

**Comment by ashokrajab** [comment]
> That's partially correct since read repair works for both vector and non-vector searches. In this regard, they don't differ because it's the same process.
Okay then, I will wait for the release with this bugfix and check whether that resolves the issue discussed [here](https://github.com/weaviate/weaviate/issues/3267#issuecomment-1645300339).

**Comment by ashokrajab** [comment]
Hi @redouan-rhazouani,

I noticed that the release (1.20.3) with the bugfix for "_vectors were not being synced to the target node_" was released. So I pulled the corresponding image and I checked whether the fix solved the issue. Yes, the fix solved the issue. But only **partially**. 

What did it fix:
1. vector attribute not being synced when repair-on-read was triggered by .with_where() query.
2. repair-on-read not being triggered for .with_near_vector() query.

What it did **NOT** fix:
1. vector attribute not being synced when repair-on-read was triggered by .with_near_vector() query.

You can find the notebook to reproduce the issue [here](https://github.com/weaviate/weaviate/files/12176556/repair_vector_issue_reproduce.zip).

Hoping this issue can also be ironed out at the earliest. Thank you for your swift actions so far.

Regards,
Ashok.

**Comment by redouan-rhazouani** [comment]
Hi @ashokrajab
The issue has been successfully resolved, as seen in the PR above. 
This fix will be included in the upcoming patch release.
Thanks for your input and collaboration

**Comment by ashokrajab** [comment]
Hello @redouan-rhazouani,

I tested the 1.20.4 release which includes the bugfix #3302. I'm happy to report that the issue mentioned [here](https://github.com/weaviate/weaviate/issues/3267#issuecomment-1652399606) has been resolved. 

I want to thank you for your quick response and actions regarding resolving this issue. I really appreciate your effort and by extension the whole Weaviate team.   

Thank you.

Regards,
Ashok.

**Comment by ashokrajab** [comment]
Hello @redouan-rhazouani,

I tested the 1.20.4 release which includes the bugfix https://github.com/weaviate/weaviate/pull/3302. I'm happy to report that the issue mentioned [here](https://github.com/weaviate/weaviate/issues/3267#issuecomment-1652399606) has been resolved.

I want to thank you for your quick response and actions regarding resolving this issue.

Regards,
Ashok

**Comment by redouan-rhazouani** [comment]
Hello @ashokrajab ,
Thank you for testing the patch release and confirming that the bugfix has resolved the issue. 
Your feedback is valuable, and I'm pleased to know that the problem has been successfully addressed.

Best regards,
Redouan
