### ISSUE TITLE
Weavaite using dokcer in colab

### ISSUE THREAD

**Issue by kulvanth5** [weaviate/weaviate#4159]
I get this error when im trying to connect to my weavaite instance present in my docker hub. Expecting that my weavaite instance should have authentication set up , i had configured authentication to a new instance and tried again. Still the same error

I had tried this in google colab notebook using udocker library in python

**{"action":"startup","error":"invalid config: no authentication scheme configured, you must select at least one","level":"error","msg":"could not load config","time":"2024-02-05T14:46:26Z"}**

**Comment by trengrj** [comment]
Hi @kulvanth5, it would be easier to use [embedded Weaviate](https://weaviate.io/developers/weaviate/installation/embedded) if you want to run inside a google colab notebook.

The error is due to no authentication scheme being configured and fix would be to set `AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true` or configure a different authentication scheme. There is documentation on important [environment variables](https://weaviate.io/developers/weaviate/installation/docker-compose#environment-variables) here. Also recently defaults were added for these values in https://github.com/weaviate/weaviate/pull/4106 which will be available in 1.24.
