### ISSUE TITLE
Vector index stats api

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#5454]
There are many stats related to HNSW in particular that would be useful to expose in a dedicated api. These stats may take some computation to calculate so it makes sense to make these separate from the nodes api which is heavily polled by clients while indexing.

Proposed stats for HNSW:

- Dimensions (h.dims)
- Entrypoint uuid
- Number of layers and distribution per layer
- Unreachable points per layer
- Current number of tombstones
- Cache size
- PQ parameters, SQ A,B parameters

**Comment by lilyTokens** [comment]
One of the more overlooked parts of production agent systems: interaction logging design. Not just 'write logs somewhere' but what schema to use, how to protect sensitive content before it hits storage, how to attach quality signals to specific interactions, and how to actually use the logs for quality improvement rather than letting them accumulate as storage cost.

Wrote up the five patterns that matter most for teams building this out: schema design, privacy-preserving logging, quality signal attachment, log-based analysis, and retention/access design.

Full write-up: https://agentskills-app.surge.sh/ai-agent-interaction-logging-design.html

**Comment by lilyTokens** [comment]
One of the more overlooked parts of production agent systems: interaction logging design. Not just 'write logs somewhere' but what schema to use, how to protect sensitive content before it hits storage, how to attach quality signals to specific interactions, and how to actually use the logs for quality improvement rather than letting them accumulate as storage cost.

Wrote up the five patterns that matter most for teams building this out: schema design, privacy-preserving logging, quality signal attachment, log-based analysis, and retention/access design.

Full write-up: https://agentskills-app.surge.sh/ai-agent-interaction-logging-design.html

**Comment by lilyTokens** [comment]
One of the more overlooked parts of production agent systems: interaction logging design. Not just 'write logs somewhere' but what schema to use, how to protect sensitive content before it hits storage, how to attach quality signals to specific interactions, and how to actually use the logs for quality improvement rather than letting them accumulate as storage cost.

Wrote up the five patterns that matter most for teams building this out: schema design, privacy-preserving logging, quality signal attachment, log-based analysis, and retention/access design.

Full write-up: https://agentskills-app.surge.sh/ai-agent-interaction-logging-design.html
